name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0, v0.1.0 etc.

jobs:
  build-and-publish:
    name: Build and publish Python distribution to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required to checkout the repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Matches python_requires from setup.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      # This will build both sdist and wheel by default into the 'dist' directory
      run: python -m build

    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} # Store your PyPI token as a secret in GitHub
      run: twine upload dist/*
